#!/bin/bash

# Accepts one pair per line, separated by :, nno first, e.g.
# bustad:bolig

# Run with first argument "inflected" to also accept input with
# inflected forms (not just lemmas), at the cost of more false
# positives to check, e.g.
#
# $ echo 'bustadene:boligene' | dev/add-words inflected > new-words.dix

if [[ $1 = inflected ]]; then
    script=add-words-inflected.awk
else
    script=add-words.awk
fi

make -q langs >&2
if [[ $? = 1 ]]; then
    cat 1>&2 <<EOF

                    # [1;31mUNCOMPILED DEPENDENCIES[0m
\$ make -j langs     # [31mDO THIS AND RERUN[0m

EOF
fi


tmpd=$(mktemp -dt apertium-add-words.XXXXXXXXXX)
echo "${tmpd}" >&2

cat >"${tmpd}/bi"

echo "${tmpd}/nno" >&2
cut -f1 -d: "${tmpd}"/bi |apertium-destxt -n |apertium -f none  -d ../apertium-nno nno-morph|apertium-retxt >"${tmpd}"/nno

echo "${tmpd}/nob" >&2
cut -f2 -d: "${tmpd}"/bi |apertium-destxt -n |apertium -f none  -d ../apertium-nob nob-morph|apertium-retxt >"${tmpd}"/nob

echo "${tmpd}/nno-known" >&2
cut -f1 -d: "${tmpd}"/bi|apertium-destxt -n |apertium -f none -d . nno-nob-morph  |apertium-retxt |grep '^\^[^*+]*\$$'|sed 's,/.*,,'|tr -d ^ >"${tmpd}"/nno-known
echo "${tmpd}/nob-known" >&2
cut -f2 -d: "${tmpd}"/bi|apertium-destxt -n |apertium -f none -d . nob-nno_e-morph|apertium-retxt |grep '^\^[^*+]*\$$'|sed 's,/.*,,'|tr -d ^ >"${tmpd}"/nob-known

awk -v tmpd="${tmpd}" -f "$(dirname "$0")"/"${script}" /dev/null
