#!/bin/bash

# Accepts one pair per line, separated by :, nno first, e.g.
# bustad:bolig

# Run with first argument "inflected" to also accept input with
# inflected forms (not just lemmas), at the cost of more false
# positives to check, e.g.
#
# $ echo 'bustadene:boligene' | dev/add-words inflected > new-words.dix

# Run with first argument a mainpos to restrict known-forms to only that
# mainpos (ie. allow "først<cnjsub>" as new word though it exists as adv/adj)

if [[ "$1" = inflected ]]; then
    knownforms () { cat ; }
    script=add-words-inflected.awk
else
    # We consider a form known by the bidix if its lemma has an analysis.
    # So grep away other forms, so we don't consider e.g. "dunst" (the noun) known just because "dunst<vblex><imp>" has an analysis:
    declare -A posrestrict
    posrestrict["vblex"]='<vblex>(<pstv>)?<inf>[$/]'
    posrestrict["n"]='<n><[mfnt]+>(<sp>|<sg><ind>)[$/]'
    posrestrict["adv"]='<adv>[$/]'
    posrestrict["cnjsub"]='<cnjsub>[$/]'
    posrestrict["ij"]='<ij>[$/]'
    posrestrict["pr"]='<pr>[$/]'
    posrestrict["np"]='<np>(<(ant|cog|top|org|al|f|m|nt)>)+'
    posrestrict["adj"]='<adj>(<sint>)?<pst><mf><sg><ind>[$/]'
    allposrestrictions=$( IFS='|'; echo "${posrestrict[*]}"; )
    if [[ -n "$1" ]]; then
        restrictions=${posrestrict[$1]}
        echo "Limiting known forms to '${restrictions}'" >&2
        knownforms () { grep -E "${restrictions}" ;}
    else
        echo "Limiting known forms to all lemma forms '${allposrestrictions}'" >&2
        knownforms () { grep -E "${allposrestrictions}" ;}
    fi
    script=add-words.awk
fi

make -q langs >&2
if [[ $? = 1 ]]; then
    cat 1>&2 <<EOF

                    # [1;31mUNCOMPILED DEPENDENCIES[0m
\$ make -j langs     # [31mDO THIS AND RERUN[0m

EOF
fi


tmpd=$(mktemp -dt apertium-add-words.XXXXXXXXXX)
echo "${tmpd}" >&2

cat >"${tmpd}/bi"

echo "${tmpd}/nno" >&2
cut -f1 -d: "${tmpd}"/bi |apertium-destxt -n |apertium -f none  -d ../apertium-nno nno-morph|apertium-retxt >"${tmpd}"/nno

echo "${tmpd}/nob" >&2
cut -f2 -d: "${tmpd}"/bi |apertium-destxt -n |apertium -f none  -d ../apertium-nob nob-morph|apertium-retxt >"${tmpd}"/nob

echo "${tmpd}/nno-known" >&2
cut -f1 -d: "${tmpd}"/bi|apertium-destxt -n |apertium -f none -d . nno-nob-morph  |apertium-retxt |grep '^\^[^*+]*\$$'| knownforms | sed 's,/.*,,'|tr -d ^ >"${tmpd}"/nno-known
echo "${tmpd}/nob-known" >&2
cut -f2 -d: "${tmpd}"/bi|apertium-destxt -n |apertium -f none -d . nob-nno_e-morph|apertium-retxt |grep '^\^[^*+]*\$$'| knownforms | sed 's,/.*,,'|tr -d ^ >"${tmpd}"/nob-known

awk -v tmpd="${tmpd}" -f "$(dirname "$0")"/"${script}" /dev/null
