#!/bin/bash

sourced () {
    [[ "$0" != "${BASH_SOURCE[0]}" ]]
}

main () {
    set -e -u
    apertium -d . nob-nno "$@"
}

declare -a vars=(
    infa_infe
    me_vi
    ggj_gg
    kj_k
    er_ar
    tek_tar
    vart_blei
    motsetning_motsetnad
)
export AP_SETVAR="$(tr ' ' ',' <<< "${vars[@]}" )"

sourced || main "$@"
