#!/bin/bash

cd "$(dirname "$0")"/.. || exit 1

while read -r w;do

    printf '[0;33m%s[0m\n' "== $w =="
    for d in {nno,nob}; do
        printf '[32m%s[0m\n' "$d: "
        echo "$w" | apertium-destxt -n | apertium -f none -d ../apertium-"$d" "$d"-morph | apertium-retxt
    done

    printf '[32m%s[0m\n' "BIDIX: "
    wb=${w// /<b\/>}
    grep --color=always "[lr]>${wb}<" ./apertium-nno-nob.nno-nob.dix
done
