#!/bin/bash

sourced () {
    [[ "$0" != "${BASH_SOURCE[0]}" ]]
}

main () {
    set -e -u
    apertium -d . nob-nno "$@"
}

declare -a vars=(
    # Monodix preferences:
    infa_infe
    me_vi
    # TODO: Dei vil ha -j- på verbet ønskje og substantivet rekkje, men ikkje dei andre
    tenkje-leggje.kons-kj2k_gj2g
    enkje_enke.kons-kj2k_gj2g
    følgje_følge.kons-lgj2lg
    # TODO: Dei vil ha lauk, men nød:
    # nød_naud.dift-ø2au
    er_ar.vb-e2a
    stader_stadar.s-pl-e2a
    dreg_drar.vb-en2tt
    tek_tar.vb-en2tt
    vart-vorte_blei-blitt.verb-bli2verte
    vit_vett
    blå_blåe
    lét_let
    nærare_nærmare.stav
    kors_kross
    fly_flyge.vb-inf
    # Bidix preferences:
    motsetning_motsetnad
    blomster_blome
    itilfelle_ifall
    veps_kvefs
    derfor_difor                # see also dess-der_di.afx in nno.dix
    skapet_skapen
    voks_vaks.vok-o2a
    mengd_mengde.vok-2e
    apa_apen
    banen_bana
    verken_korkje
    røyndom_røynd
    beskrive_skildre
    oversikt_oversyn
    mørke_mørker.stav
    stemme_røyste
    gjenfortelje_attfortelje
    mark_makk
    nærast_nærmast
    stemmerett_røysterett
)
export AP_SETVAR="$(tr ' ' ',' <<< "${vars[@]}" )"


# Simple sanity test, shout if we can't find all the variable names in one of monodix and biprefs
selftest () {
    (
        cd "$(dirname "${BASH_SOURCE[0]}")"/..
        if [[ ! -f ../apertium-nno/apertium-nno.nno.dix ]]; then
            echo "$PWD/../apertium-nno/apertium-nno.nno.dix doesn't exist, skipping selftest"
            return
        fi
        for varWithVal in "${vars[@]}"; do
            var="${varWithVal%%=*}"
            grep -q -w -F "VAR:${var}" apertium-nno-nob.nob-nno.biprefs.rlx          \
            || grep -q -F "sdef n=\"v:${var}\"" ../apertium-nno/apertium-nno.nno.dix \
            || echo "WARNING: v:${var} not found in nno.dix nor biprefs.rlx" >&2
        done
    )
}


if sourced; then
    selftest
else
    main "$@"
fi
