#!/bin/bash

sourced () {
    [[ "$0" != "${BASH_SOURCE[0]}" ]]
}

main () {
    set -e -u
    apertium -d . nob-nno "$@"
}

declare -a vars=(
    # Monodix preferences:
    infa_infe
    me_vi
    # TODO: Dei vil ha -j- på verbet ønskje og substantivet rekkje, men ikkje dei andre
    tenkje-leggje.kons-kj2k_gj2g
    # dess-der_di.afx             # TODO: Cappelen vil berre ha derfor→difor, ikkje «di galnare» eller «dimed»
    enkje_enke.kons-kj2k_gj2g
    følgje_følge.kons-lgj2lg
    # TODO: Dei vil ha lauk, men nød:
    # nød_naud.dift-ø2au
    er_ar.vb-e2a
    stader_stadar.n-pl-e2a
    dreg_drar.vb-en2tt
    dratt_dradd.vb-en2tt
    tek_tar.vb-en2tt
    vart-vorte_blei-blitt.vb-bli2verte
    vit_vett
    blå_blåe.adj
    lét_let
    nærare_nærmare.stav
    kors_kross.stav
    fly_flyge.vb-inf
    brukte_bruka.vb-e2a=dynge:skylde:bie:fordøye
    # Bidix preferences:
    motsetning_motsetnad.syn
    blomster_blome.syn
    itilfelle_ifall
    veps_kvefs.syn
    voks_vaks.vok-o2a
    mengd_mengde.vok-2e
    banen_bana.n-m2f=bane:kai:opptakt:tillit:dialekt
    lova_loven.n.f2m=ape:kasse:olje:festning
    verken_korkje.syn
    beskrive_skildre            # TODO: skrudd av for no pga. manglande disambiguering jf. kommentar i biprefs.rlx
    oversikt_oversyn.syn
    mørke_mørker.stav
    stemme_røyste.syn
    gjenfortelje_attfortelje
    mark_makk
    nærast_nærmast
)
export AP_SETVAR="$(tr ' ' ',' <<< "${vars[@]}" )"


# Simple sanity test, shout if we can't find all the variable names in one of monodix and biprefs
selftest () {
    (
        cd "$(dirname "${BASH_SOURCE[0]}")"/..
        if [[ ! -f ../apertium-nno/apertium-nno.nno.dix ]]; then
            echo "$PWD/../apertium-nno/apertium-nno.nno.dix doesn't exist, skipping selftest"
            return
        fi
        for varWithVal in "${vars[@]}"; do
            var="${varWithVal%%=*}"
            grep -q -w -F "VAR:${var}" apertium-nno-nob.nob-nno.biprefs.rlx          \
            || grep -q -F "sdef n=\"v:${var}\"" ../apertium-nno/apertium-nno.nno.dix \
            || echo "WARNING: v:${var} not found in nno.dix nor biprefs.rlx" >&2
        done
    )
}


if sourced; then
    selftest
else
    main "$@"
fi
