#!/bin/bash

sourced () {
    [[ "$0" != "${BASH_SOURCE[0]}" ]]
}

main () {
    set -e -u
    apertium -d . nob-nno "$@"
}

declare -a vars=(
    # Monodix preferences:
    infa_infe
    me_vi
    ggj_gg
    kj_k
    er_ar
    tek_tar
    vart_blei
    vit_vett
    blå_blåe
    lét_let
    løk_lauk
    nærare_nærmare
    kors_kross
    fly_flyge
    flyr_flyg
    # Bidix preferences:
    motsetning_motsetnad
    kviss_quiz
    blomster_blome
    itilfelle_ifall
    veps_kvefs
    derfor_difor
    skapet_skapen
    voks_vaks
    mengd_mengde
    apa_apen
    banen_bana
    verken_korkje
    røyndom_røynd
    beskrive_skildre
    oversikt_oversyn
    mørke_mørker
    stemme_røyste
    gjenfortelje_attfortelje
    mark_makk
    nærast_nærmast
    stemmerett_røysterett
)
export AP_SETVAR="$(tr ' ' ',' <<< "${vars[@]}" )"

sourced || main "$@"
