#!/bin/bash

# Run with -f to show only failing tests

set -e -u

source "$(dirname $0)"/config.sh

for pair in "${PAIRS[@]}"; do
    bash "$(dirname $0)"/wiki-tests -u "$@" Regression "${pair}"
done
