#+TITLE: Reuse of Free Resources in Machine Translation between Norwegian Nynorsk and Bokmål
#+OPTIONS: skip:nil num:nil author:nil
#+EMAIL: unhammer at gmail dot com
#+LANGUAGE: en
#+TAGS: ROTETE(r)
#+EXPORT_EXCLUDE_TAGS: ROTETE
#+LaTeX_CLASS: freerbmt
#+LaTeX_HEADER: \usepackage{hyperref}
#+LaTeX_HEADER: \author{Jane Doe\\  Department of Computer Science \\  Nonesuch State University \\  Utopia, NS 12345 \\  {\tt jane.doe@cs.nsu.edu} \And  John Smith \\  Department of Linguistics \\  Another State University \\  Collegetown, AS 98765 \\    {\tt jsmith@ling.asu.edu}}

#+BEGIN_LaTeX
\begin{abstract}

  This article has a very long title, which should probably be snappier and more enticing since we want people to read the abstract to find out what it's really all about.
\end{abstract}
#+END_LaTeX

* Introduction
The term /Norwegian/ covers a variety of related spoken dialects. Up
until the 1800's, Danish was the only written standard used in
Norway. Bokmål emerged through various reforms which brought the
written language closer to the spoken; Nynorsk however, was created
from the ground up with the purpose of representing all the spoken
dialects of Norway. As it is, certain dialects (especially around the
Oslo area) correspond more with Bokmål, while others are closer to
Nynorsk. Nynorsk is "in a minority position in Norway, with
approximately 12% of the users" \citep{everson2000sln}, or around
450,000 people. 

The source code and linguistic data in Apertium and its language pairs
are released as free and open source software. Although Nynorsk is in
a minority position, there are quite good linguistic resources
available under Free licences, compared to many languages with the
same amount of speakers. 

We describe the creation of a machine translation system between
Nynorsk and Bokmål built using the free and open source Apertium
platform \citep{corbi05oss}. In \ref{sec-1} we ...
** TODO give overview/roadmap of the article



* Design (just a very short intro to the Apertium pipeline here?)
The nn-nb language pair follows the design of the Apertium system
\citep{corbi05oss}, a highly modular shallow-transfer pipeline
system. Dictionaries written in XML are compiled into reversible
finite state transducers, so that word-for-word translations are
possible in both directions using only two monolingual and one
translational (transfer) dictionary. First order hidden Markov models
are used for POS tagging. The transfer module is finite state based
and allows three-stage chunking transfer (although nn-nb only uses
one-stage transfer). De-/reformatters applied to the beginning and end
of the pipeline lets one preserve formatting of various document
types.

The nn-nb language pair differs from most of the other Apertium pairs
in having a Constraint Grammar module as a pre-disambiguator (before
the statistical tagger).


* Development
** Resources
We used the GPL-ed resources Norsk Ordbank[fn:2], a $>100,000$ lemma
full form dictionary and, the Oslo-Bergen Tagger \citep{hagen2000cbt},
a high quality Constraint Grammar disambiguator. These were converted
into Apertium formats and tag schemes. We found no freely available
bilingual dictionary, so this was created using various both manual
and automatic methods, along with transfer rules to cope with
syntactic differences and agreement.

** Analysis and generation

** Disambiguation

** Lexical transfer

- exact matches "adding exact matches if morphology is the same
  e.g. if a noun is (sg.ind, pl.ind, sg.def, pl.def) in both
  languages and is spelt the same then added to the bidix"
- matches with differences a lot of bidix entries were created by
  1.finding nb entries w/o translations
  1. running some replacements for typical differences in substrings
  2. checking whether the altered entries were in nn
  \citet[p.~4]{tyers2009dpm} used the same method, but additionally:
- Giza++ (I guess I could do a diff on the bidix from before and after
  I started working on Giza++ stuff)
- Anything about regression testing and that stuff? (Ie. whenever we
  fix a certain transfer construction or disambiguation problem, we
  add a regression test to make sure we don't have to fix it again.)

** Syntactic transfer
- what are the relevant patterns which need transfer?
- how did we solve it?
- how didn't we solve it? (or, what are the problems)


* Evaluation
We define naïve coverage as the proportion of words in a corpus which
are given at least one analysis by our monolingual
dictionaries. Testing on Nynorsk Wikipedia (5116174 words) and Bokmål
Wikipedia (27529115 words), we have 89.6% and 88.2% coverage,
respectively.

The Word Error Rate (WER) on a 3750 word Wikipedia article on
linguistics in the Bokmål to Nynorsk direction was 22.06% when
including unknown words, although since 64.93% of these were
free-rides (ie. the same in Bokmål and Nynorsk) anyway, the final WER
was 10.71%. Typical free-rides include names, loan-words and special
terminology.

- Qualitative assessment...
  - Error types:
    - lexical selection
    - disambiguation
    - transfer (eg. word order, "mannen sin hest")

- Anything about Nyno? (Their web page says 74000 words, don't know
  about WER but the cool thing about Nyno is the interface, ie. the
  freedom of choice with variants and how the user can do the lexical
  selection. 
* outdated..							     :ROTETE:
  The examples from
  http://www.hf.uio.no/tekstlab/Presseklipp/Spr%E5knytt%203-2001.htm
  ("Nyno i bruk") seem to indicate that the OBT is a bit better at
  disambiguating though (underline meaning wrong translation):
  - Original: Når det iverksettes arbeidskamp, er det partene i den
    enkelte tvist som har ansvaret for de konsekvenser arbeidskamp
    påfører tredjemann.
  - Nyno: Når _den iverksettes arbeidskampen_, er _dei_ partane i den
    enkelte tvist som har ansvaret for dei konsekvensane arbeidskamp
    påfører tredjemann.
  - Apertium: Når det blir iverksett *arbeidskamp, er det partane i
    den einskilde tvisten som har ansvaret for dei konsekvensane
    *arbeidskamp påfører tredjemann.

* Discussion
- We don't have any sort of compound handling, probably we could
  analyse a whole lot more with a trie or whatever, but there's also a
  compound handler in OBT that might be possible to integrate.
  - *menneskehandel.
  - menneske. handel.
- "Well-written" nynorsk uses lots of periphrasis and MWE's, eg. particle
  verbs; we don't generate any such thing. A syntactic analysis might
  be useful here, although without being quite certain of where the
  relevant phrase ends, it'll be safer to stick with non-discontinuous
  target language translations.

On the Scandinavian language group, and expanding it for Apertium:
#+BEGIN_QUOTE 
Morphologically, these four languages are equally distant from each
other, but the terminological differences are smaller between Nynorsk
and Bokmål than between the other two. \\
\citep{everson2000sln}
#+END_QUOTE

* TODO Acknowledgements should be section*			     :ROTETE:
* Acknowledgements 
Development was funded as part of the Google Summer of Code[fn:1]
programme. Thanks to mentors and OBT people.

\bibliographystyle{apalike}
\bibliography{apertium}


* Footnotes

[fn:1] http://code.google.com/soc/

[fn:2] http://www.edd.uio.no/prosjekt/ordbanken/



