#+TITLE: Reuse of Free Resources in Machine Translation between Norwegian Nynorsk and Bokmål
#+OPTIONS: skip:nil num:nil author:nil
#+EMAIL: unhammer at gmail dot com
#+LANGUAGE: en
#+TAGS: ROTETE(r)
#+EXPORT_EXCLUDE_TAGS: ROTETE
#+LaTeX_CLASS: freerbmt
#+LaTeX_HEADER: \usepackage{hyperref}
#+LaTeX_HEADER: \author{Jane Doe\\  Department of Computer Science \\  Nonesuch State University \\  Utopia, NS 12345 \\  {\tt jane.doe@cs.nsu.edu} \And  John Smith \\  Department of Linguistics \\  Another State University \\  Collegetown, AS 98765 \\    {\tt jsmith@ling.asu.edu}}

#+BEGIN_LaTeX
\begin{abstract}

  This article has a very long title, which should probably be snappier and more enticing since we want people to read the abstract to find out what it's really all about.
\end{abstract}
#+END_LaTeX

* Introduction
The term /Norwegian/ covers a variety of related spoken dialects. Up
until the 1800's, Danish was the only written standard used in
Norway. Bokmål emerged through various reforms which brought the
written language closer to the spoken; Nynorsk however, was created
from the ground up with the purpose of representing all the spoken
dialects of Norway. As it is, certain dialects (especially around the
Oslo area) correspond more with Bokmål, while others are closer to
Nynorsk. Nynorsk is "in a minority position in Norway, with
approximately 12% of the users" \citep{everson2000sln}, or around
450,000 people. 

We describe a machine translation system between Nynorsk and Bokmål
built using the Apertium platform \citep{corbi05oss}...

Although Nynorsk is in a minority position, there are quite good
linguistic resources for both Nynorsk and Bokmål available under Free
licences.

The Oslo-Bergen Tagger \citep{hagen2000cbt} ...


On the Scandinavian language group, and expanding it for Apertium:
#+BEGIN_QUOTE 
Morphologically, these four languages are equally distant from each
other, but the terminological differences are smaller between Nynorsk
and Bokmål than between the other two. \\
\citep{everson2000sln}
#+END_QUOTE






* Design
The nn-nb module follows the design of the Apertium
system\citep{corbi05oss}, a shallow-transfer pipeline system. Apertium is
quite modular, and nn-nb differs from most of the other language pairs
in using a Constraint Grammar morphological disambiguator.
* Development
- exact matches "adding exact matches if morphology is the same
  e.g. if a noun is (sg.ind, pl.ind, sg.def, pl.def) in both
  languages and is spelt the same then added to the bidix"
- matches with differences a lot of bidix entries were created by
  1.finding nb entries w/o translations
  2. running some replacements for typical differences in substrings
  3. checking whether the altered entries were in nn
- Giza++ (I guess I could do a diff on the bidix from before and after
  I started working on Giza++ stuff)


* Evaluation
We define naïve coverage as the proportion of words in a corpus which
are given at least one analysis by our monolingual
dictionaries. Testing on Nynorsk Wikipedia (5116174 words) and Bokmål
Wikipedia (27529115 words), we have 89.6% and 88.2% coverage,
respectively.

The Word Error Rate (WER) on a 3750 word Wikipedia article on
linguistics in the Bokmål to Nynorsk direction was 22.06% when
including unknown words, although since 64.93% of these were
free-rides (ie. the same in Bokmål and Nynorsk) anyway, the final WER
was 10.71%. Typical free-rides include names, loan-words and special
terminology.

- Qualitative assessment...

- anything else?

* Discussion
- We don't have any sort of compound handling, probably we could
  analyse a whole lot more with a trie or whatever, but there's also a
  compound handler in OBT that might be possible to integrate.
  - *menneskehandel.
  - menneske. handel.
- "Well-written" nynorsk uses lots of periphrasis and MWE's, eg. particle
  verbs; we don't generate any such thing. A syntactic analysis might
  be useful here, although without being quite certain of where the
  relevant phrase ends, it'll be safer to stick with non-discontinuous
  target language translations.

* TODO Acknowledgements should be section*			     :ROTETE:
* Acknowledgements 
Development was funded as part of the Google Summer of Code[fn:1]
programme. Thanks to mentors and OBT people.

\bibliographystyle{apalike}
\bibliography{apertium}


* Footnotes

[fn:1] http://code.google.com/soc/

